from typing import Any

from app.skills.base import BaseSkill, CodeArtifact, SkillCategory, SkillParameter, SkillResult
from app.skills.registry import SkillRegistry


@SkillRegistry.register
class GoTestSuiteSkill(BaseSkill):
    name = "go.test_suite"
    description = (
        "Generate Go unit tests with testify/suite and table-driven patterns, "
        "plus mockery-generated mocks for the repository interface."
    )
    category = SkillCategory.GO
    tags = ["go", "test", "testify", "mockery", "unit-test", "tdd", "suite"]
    parameters = [
        SkillParameter("resource", "Resource name in singular form (e.g. user, product, order)"),
        SkillParameter("module_name", "Go module name", required=False, default="github.com/org/app"),
    ]

    async def execute(  # type: ignore[override]
        self,
        resource: str,
        module_name: str = "github.com/org/app",
        **_: Any,
    ) -> SkillResult:
        r = resource.lower().replace("-", "_").replace(" ", "_")
        R = r.capitalize()

        mock_code = (
            "// Code generated by mockery v2. DO NOT EDIT.\n"
            "package mocks\n\n"
            "import (\n"
            "\t\"context\"\n\n"
            "\t\"github.com/stretchr/testify/mock\"\n\n"
            f"\t\"{module_name}/internal/domain\"\n"
            ")\n\n"
            f"type Mock{R}Repository struct {{\n"
            "\tmock.Mock\n"
            "}\n\n"
            f"func (m *Mock{R}Repository) FindByID(ctx context.Context, id int64) (*domain.{R}, error) {{\n"
            "\targs := m.Called(ctx, id)\n"
            f"\tif args.Get(0) == nil {{\n"
            f"\t\treturn nil, args.Error(1)\n"
            f"\t}}\n"
            f"\treturn args.Get(0).(*domain.{R}), args.Error(1)\n"
            "}\n\n"
            f"func (m *Mock{R}Repository) FindAll(ctx context.Context, limit, offset int) ([]*domain.{R}, error) {{\n"
            "\targs := m.Called(ctx, limit, offset)\n"
            f"\tif args.Get(0) == nil {{\n"
            f"\t\treturn nil, args.Error(1)\n"
            f"\t}}\n"
            f"\treturn args.Get(0).([]*domain.{R}), args.Error(1)\n"
            "}\n\n"
            f"func (m *Mock{R}Repository) Create(ctx context.Context, req domain.Create{R}Request) (*domain.{R}, error) {{\n"
            "\targs := m.Called(ctx, req)\n"
            f"\tif args.Get(0) == nil {{\n"
            f"\t\treturn nil, args.Error(1)\n"
            f"\t}}\n"
            f"\treturn args.Get(0).(*domain.{R}), args.Error(1)\n"
            "}\n\n"
            f"func (m *Mock{R}Repository) Update(ctx context.Context, id int64, req domain.Update{R}Request) (*domain.{R}, error) {{\n"
            "\targs := m.Called(ctx, id, req)\n"
            f"\tif args.Get(0) == nil {{\n"
            f"\t\treturn nil, args.Error(1)\n"
            f"\t}}\n"
            f"\treturn args.Get(0).(*domain.{R}), args.Error(1)\n"
            "}\n\n"
            f"func (m *Mock{R}Repository) Delete(ctx context.Context, id int64) error {{\n"
            "\targs := m.Called(ctx, id)\n"
            "\treturn args.Error(0)\n"
            "}\n"
        )

        service_test_code = (
            "package service_test\n\n"
            "import (\n"
            "\t\"context\"\n"
            "\t\"testing\"\n"
            "\t\"time\"\n\n"
            "\t\"github.com/stretchr/testify/suite\"\n\n"
            f"\t\"{module_name}/internal/domain\"\n"
            f"\t\"{module_name}/internal/service\"\n"
            f"\t\"{module_name}/internal/mocks\"\n"
            ")\n\n"
            f"type {R}ServiceSuite struct {{\n"
            "\tsuite.Suite\n"
            f"\tmock *mocks.Mock{R}Repository\n"
            f"\tsvc  *service.{R}Service\n"
            "}\n\n"
            f"func (s *{R}ServiceSuite) SetupTest() {{\n"
            f"\ts.mock = &mocks.Mock{R}Repository{{}}\n"
            f"\ts.svc = service.New{R}Service(s.mock)\n"
            "}\n\n"
            f"func Test{R}Service(t *testing.T) {{\n"
            f"\tsuite.Run(t, new({R}ServiceSuite))\n"
            "}}\n\n"
            f"func (s *{R}ServiceSuite) Test_Get_Found() {{\n"
            f"\tentity := &domain.{R}{{ID: 1, Name: \"test\", CreatedAt: time.Now(), UpdatedAt: time.Now()}}\n"
            f"\ts.mock.On(\"FindByID\", context.Background(), int64(1)).Return(entity, nil)\n"
            f"\tresult, err := s.svc.Get(context.Background(), 1)\n"
            "\ts.NoError(err)\n"
            "\ts.Equal(entity.ID, result.ID)\n"
            "}\n\n"
            f"func (s *{R}ServiceSuite) Test_Create_EmptyName_Fails() {{\n"
            f"\t_, err := s.svc.Create(context.Background(), domain.Create{R}Request{{}})\n"
            "\ts.Error(err)\n"
            f'\ts.Contains(err.Error(), "name is required")\n'
            "}\n\n"
            f"func (s *{R}ServiceSuite) Test_Create_Success() {{\n"
            f"\treq := domain.Create{R}Request{{Name: \"test item\"}}\n"
            f"\tentity := &domain.{R}{{ID: 1, Name: \"test item\", CreatedAt: time.Now(), UpdatedAt: time.Now()}}\n"
            f"\ts.mock.On(\"Create\", context.Background(), req).Return(entity, nil)\n"
            f"\tresult, err := s.svc.Create(context.Background(), req)\n"
            "\ts.NoError(err)\n"
            "\ts.Equal(int64(1), result.ID)\n"
            "}\n"
        )

        mockery_config = (
            "with-expecter: true\n"
            "dir: internal/mocks\n"
            "packages:\n"
            f"  {module_name}/internal/repository:\n"
            "    interfaces:\n"
            f"      {R}Repository:\n"
        )

        return SkillResult(
            success=True,
            summary=f"Generated testify suite tests and mockery mock for `{R}`",
            artifacts=[
                CodeArtifact(
                    filename=f"internal/mocks/mock_{r}_repository.go",
                    content=mock_code,
                    language="go",
                    description=f"Mockery mock for {R}Repository",
                ),
                CodeArtifact(
                    filename=f"internal/service/{r}_service_test.go",
                    content=service_test_code,
                    language="go",
                    description=f"testify/suite tests for {R}Service",
                ),
                CodeArtifact(
                    filename=".mockery.yaml",
                    content=mockery_config,
                    language="yaml",
                    description="Mockery code-generation config",
                ),
            ],
            dev_dependencies=["github.com/stretchr/testify", "github.com/vektra/mockery/v2"],
            instructions=[
                "Run `go test ./... -race -cover` to execute tests",
                "Run `mockery --config=.mockery.yaml` to regenerate mocks",
            ],
        )
